name: produts
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  chopper: ^4.0.5
  flutter:
    sdk: flutter
  freezed_annotation: ^1.1.0
  intl: ^0.17.0
  http: ^0.13.4
  json_annotation: ^4.4.0
  equatable: ^2.0.3
  flutter_bloc: ^8.0.0
  
  flutter_lints: ^1.0.4

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  build_runner: 2.1.8
  chopper_generator: null
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  json_serializable: 6.1.5

flutter:
  uses-material-design: true

  # # Enable generation of localized Strings from arb files.
  # generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

dependency_overrides:
  analyzer: 3.3.1
flutter_intl:
  enabled: true
